# Generated by Django 2.2.7 on 2019-11-12 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='instance_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='page',
            name='version',
            field=models.FloatField(default=1.0, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('instance_id', 'version')},
        ),
    ]
