# Generated by Django 2.2.7 on 2019-11-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191112_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='version',
            field=models.FloatField(default=1.0),
        ),
    ]
