# Generated by Django 2.2.7 on 2019-11-12 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191112_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='instance_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
