# Generated by Django 2.2.7 on 2019-11-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191112_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='instance_id',
            new_name='thread_id',
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('thread_id', 'version')},
        ),
    ]
