# Generated by Django 2.2.7 on 2019-11-12 16:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191112_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='thread_id',
            field=models.IntegerField(default=1),
        ),
    ]
