# Generated by Django 2.2.7 on 2019-11-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20191113_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='versions_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.VersionsThread'),
        ),
    ]
