# Generated by Django 2.2.7 on 2019-11-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20191113_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='versions_thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pages', to='pages.VersionsThread'),
            preserve_default=False,
        ),
    ]
